### ISSUE TITLE
在demo网页没法搜索D版内容，请问是被屏蔽了吗？

### ISSUE THREAD

**Issue by ljq29** [fqxufo/hipda-simple-search#1]
可以看到加载D版数据库，但是没有搜索按钮。

**Comment by fqxufo** [comment]
https://github.com/fqxufo/hipda-simple-search/commit/8b9cd3ff52da5ce366b7242ba6856185cb0ae924
f12食用

**Comment by ljq29** [comment]
> [8b9cd3f](https://github.com/fqxufo/hipda-simple-search/commit/8b9cd3ff52da5ce366b7242ba6856185cb0ae924)
> f12食用

看不懂啊大佬，我看magic code: app.showd 已经 = true 了啊

**Comment by fqxufo** [comment]
f12 -> Console -> app.showd = true

**Comment by ljq29** [comment]
成了，谢谢大佬！
