### ISSUE TITLE
大佬考不考虑增加多关键词的功能？

### ISSUE THREAD

**Issue by ljq29** [fqxufo/hipda-simple-search#2]
RTRT，用空格键分割关键词。

**Comment by fqxufo** [comment]
我不会sql,现学的,现在是这么实现的搜索:
`SELECT * FROM 'titles' where title like '%关键词%' ORDER BY tid DESC`

老哥你可以在这个网站在线试试:https://inloop.github.io/sqlite-viewer/,
数据库文件就用这个https://github.com/fqxufo/hipda-simple-search/blob/master/titles_D.db,
搞成功了把sql语句发出来我就加上去

**Comment by ljq29** [comment]
select * from 'titles' where * in (select * from 'titles' where title like '%关键词2%') and title like '%关键词1%'
参考这里写的：https://zhidao.baidu.com/question/2122944099789611667.html
可以考虑先弄出来两个关键词的？我这个可能不太对，主要是之前没接触过sql语句。

**Comment by fqxufo** [comment]
已经初步实现了，现在支持两个关键词

**Comment by ljq29** [comment]
> 已经初步实现了，现在支持两个关键词

大佬就是大佬，佩服！
