### ISSUE TITLE
无法显示完全

### ISSUE THREAD

**Issue by yefeiyu** [fqxufo/hipda-simple-search#3]
![3D3F934A-AD31-42E3-93A5-4F5B379C626B](https://user-images.githubusercontent.com/4845104/77488972-c3967a00-6e71-11ea-9869-ecc76fa5f789.png)
![5C81002B-E562-43DA-AB7F-49A357928FC2](https://user-images.githubusercontent.com/4845104/77488981-c6916a80-6e71-11ea-98c3-e057302d7050.png)
只显示bs搜索标签

**Comment by fqxufo** [comment]
等一分钟有惊喜
