### ISSUE TITLE
不能搜索

### ISSUE THREAD

**Issue by babyhux** [fqxufo/hipda-simple-search#4]
提示D版索引未加载,请稍后 
然后无法搜索  还有维护吗

**Comment by fqxufo** [comment]
多刷新一下，这个完全是前端下载数据库文件再解析的，文件越来越大后速度很慢了

PS：D版自己的搜索应该是恢复了，你可以回去看看

**Comment by babyhux** [comment]
hipda自己的搜索还是不行的。。。那我多刷新吧发自我的iPhone------------------ 原始邮件 ------------------发件人: fqxufo  ***@***.***>发送时间: 2022年2月15日 22:40收件人: fqxufo/hipda-simple-search ***@***.***>抄送: babyhux ***@***.***>, Author ***@***.***>主题: Re: [fqxufo/hipda-simple-search] 不能搜索 (Issue #4)
多刷新一下，这个完全是前端下载数据库文件再解析的，文件越来越大后速度很慢了
PS：D版自己的搜索应该是恢复了，你可以回去看看

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/fqxufo/hipda-simple-search/issues/4#issuecomment-1040352162",
"url": "https://github.com/fqxufo/hipda-simple-search/issues/4#issuecomment-1040352162",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by fqxufo** [comment]
https://greasyfork.org/zh-CN/scripts/415476-hipda%E6%90%9C%E7%B4%A2%E8%B6%85%E8%83%BD%E5%8A%9B

安装我这个油猴脚本试试吧
