### ISSUE TITLE
烦请修改搜索结果的链接域名，谢谢

### ISSUE THREAD

**Issue by Flaxtonchn** [fqxufo/hipda-simple-search#5]
RT

**Comment by fqxufo** [comment]
D版自己的搜索已经恢复，没必要继续用我这个了

**Comment by Flaxtonchn** [comment]
> D版自己的搜索已经恢复，没必要继续用我这个了

收到。刚去试了一下才发现恢复了。感谢这些年一直用您这个脚本，很方便。现在还在用那个浏览器扩展
