### ISSUE TITLE
change hi-pda site domain to 4d4y.com

### ISSUE THREAD

**Issue by Owisky** [fqxufo/hipda-simple-search#6]
hi-pda forum has changed the banding domain to 4d4y.com

sed - i * "s/hi-pda.com/4d4y.com/g"

**Comment by fqxufo** [comment]
HIpda（现4d4y）的自带搜索已经恢复，没有必要使用本项目了，而且本项目22年3月之后就没有维护，索引数据没有更新了

**Comment by fqxufo** [comment]
当然您想继续使用，可以简单修改域名，在本地运行即可，同目录中建立‘pwd.json'文件，写入账户密码，使用crond定期运行

`with open('pwd.json','r') as f:
        data = json.load(f)

    USERNAME = data['USERNAME']
    PWD = data['PWD']`
